spring:
  application:
    name: board-example

  datasource:
    url: jdbc:mysql://localhost:3306/project_board
      ?useSSL=false
      &serverTimezone=Asia/Seoul
      &useUnicode=true
      &characterEncoding=utf8
      &allowPublicKeyRetrieval=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    template:
      fetch-size: 100
      max-rows: 1000

  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc.core: debug