spring:
  application:
    name: spring-mvc-study-servlet

  datasource:
    url: jdbc:mysql://localhost:3306/
      ?useSSL=false
      &serverTimezone=Asia/Seoul
      &useUnicode=true
      &characterEncoding=utf8
      &allowPublicKeyRetrieval=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari dataSource option
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jdbc:
    template:
      fetch-size: 100
      max-rows: 1000

  thymeleaf:
    cache: false

server:
  port: 9999

logging:
  level:
#    org.springframework.jdbc.core: debug
    org.apache.coyote.http11: trace # coyote.http11 = HTTP 파싱/프로세서/버퍼
    org.apache.tomcat.util.net: debug # NIO endpoint/socket